export const CALCULATION_LIST_REQUEST = 'CALCULATION_LIST_REQUEST'
export const CALCULATION_LIST_SUCCESS = 'CALCULATION_LIST_SUCCESS'
export const CALCULATION_LIST_FAIL = 'CALCULATION_LIST_FAIL'

export const CALCULATION_DETAILS_REQUEST = 'CALCULATION_DETAILS_REQUEST'
export const CALCULATION_DETAILS_SUCCESS = 'CALCULATION_DETAILS_SUCCESS'
export const CALCULATION_DETAILS_FAIL = 'CALCULATION_DETAILS_FAIL'
